// Generated by gencpp from file catbot_navigation/GoToGoalGoal.msg
// DO NOT EDIT!


#ifndef CATBOT_NAVIGATION_MESSAGE_GOTOGOALGOAL_H
#define CATBOT_NAVIGATION_MESSAGE_GOTOGOALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace catbot_navigation
{
template <class ContainerAllocator>
struct GoToGoalGoal_
{
  typedef GoToGoalGoal_<ContainerAllocator> Type;

  GoToGoalGoal_()
    : x_pos(0.0)
    , y_pos(0.0)
    , theta(0.0)  {
    }
  GoToGoalGoal_(const ContainerAllocator& _alloc)
    : x_pos(0.0)
    , y_pos(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_pos_type;
  _x_pos_type x_pos;

   typedef double _y_pos_type;
  _y_pos_type y_pos;

   typedef double _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GoToGoalGoal_

typedef ::catbot_navigation::GoToGoalGoal_<std::allocator<void> > GoToGoalGoal;

typedef boost::shared_ptr< ::catbot_navigation::GoToGoalGoal > GoToGoalGoalPtr;
typedef boost::shared_ptr< ::catbot_navigation::GoToGoalGoal const> GoToGoalGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace catbot_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'catbot_navigation': ['/home/ganam/s/devel/share/catbot_navigation/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5af55a02225d2e56be88e5e3a36b4ce9";
  }

  static const char* value(const ::catbot_navigation::GoToGoalGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5af55a02225d2e56ULL;
  static const uint64_t static_value2 = 0xbe88e5e3a36b4ce9ULL;
};

template<class ContainerAllocator>
struct DataType< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "catbot_navigation/GoToGoalGoal";
  }

  static const char* value(const ::catbot_navigation::GoToGoalGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Definition of Goal Message\n\
\n\
float64 x_pos\n\
float64 y_pos\n\
float64 theta\n\
";
  }

  static const char* value(const ::catbot_navigation::GoToGoalGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GoToGoalGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::catbot_navigation::GoToGoalGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::catbot_navigation::GoToGoalGoal_<ContainerAllocator>& v)
  {
    s << indent << "x_pos: ";
    Printer<double>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<double>::stream(s, indent + "  ", v.y_pos);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CATBOT_NAVIGATION_MESSAGE_GOTOGOALGOAL_H
