(cl:defpackage catbot_navigation-msg
  (:use )
  (:export
   "<GOTOGOALACTION>"
   "GOTOGOALACTION"
   "<GOTOGOALACTIONFEEDBACK>"
   "GOTOGOALACTIONFEEDBACK"
   "<GOTOGOALACTIONGOAL>"
   "GOTOGOALACTIONGOAL"
   "<GOTOGOALACTIONRESULT>"
   "GOTOGOALACTIONRESULT"
   "<GOTOGOALFEEDBACK>"
   "GOTOGOALFEEDBACK"
   "<GOTOGOALGOAL>"
   "GOTOGOALGOAL"
   "<GOTOGOALRESULT>"
   "GOTOGOALRESULT"
  ))

