; Auto-generated. Do not edit!


(cl:in-package catbot_navigation-msg)


;//! \htmlinclude GoToGoalResult.msg.html

(cl:defclass <GoToGoalResult> (roslisp-msg-protocol:ros-message)
  ((targetReached
    :reader targetReached
    :initarg :targetReached
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GoToGoalResult (<GoToGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GoToGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GoToGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name catbot_navigation-msg:<GoToGoalResult> is deprecated: use catbot_navigation-msg:GoToGoalResult instead.")))

(cl:ensure-generic-function 'targetReached-val :lambda-list '(m))
(cl:defmethod targetReached-val ((m <GoToGoalResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader catbot_navigation-msg:targetReached-val is deprecated.  Use catbot_navigation-msg:targetReached instead.")
  (targetReached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GoToGoalResult>) ostream)
  "Serializes a message object of type '<GoToGoalResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'targetReached) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GoToGoalResult>) istream)
  "Deserializes a message object of type '<GoToGoalResult>"
    (cl:setf (cl:slot-value msg 'targetReached) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GoToGoalResult>)))
  "Returns string type for a message object of type '<GoToGoalResult>"
  "catbot_navigation/GoToGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GoToGoalResult)))
  "Returns string type for a message object of type 'GoToGoalResult"
  "catbot_navigation/GoToGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GoToGoalResult>)))
  "Returns md5sum for a message object of type '<GoToGoalResult>"
  "b7405910e0e48bc9fe5218f5d63db25f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GoToGoalResult)))
  "Returns md5sum for a message object of type 'GoToGoalResult"
  "b7405910e0e48bc9fe5218f5d63db25f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GoToGoalResult>)))
  "Returns full string definition for message of type '<GoToGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Definition of Result Message~%bool targetReached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GoToGoalResult)))
  "Returns full string definition for message of type 'GoToGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Definition of Result Message~%bool targetReached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GoToGoalResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GoToGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GoToGoalResult
    (cl:cons ':targetReached (targetReached msg))
))
