// Auto-generated. Do not edit!

// (in-package catbot_navigation.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class GoToGoalResult {
  constructor() {
    this.targetReached = false;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type GoToGoalResult
    // Serialize message field [targetReached]
    bufferInfo = _serializer.bool(obj.targetReached, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type GoToGoalResult
    let tmp;
    let len;
    let data = new GoToGoalResult();
    // Deserialize message field [targetReached]
    tmp = _deserializer.bool(buffer);
    data.targetReached = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'catbot_navigation/GoToGoalResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b7405910e0e48bc9fe5218f5d63db25f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Definition of Result Message
    bool targetReached
    
    `;
  }

};

module.exports = GoToGoalResult;
