// Auto-generated. Do not edit!

// (in-package catbot_navigation.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class GoToGoalGoal {
  constructor() {
    this.x_pos = 0.0;
    this.y_pos = 0.0;
    this.theta = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type GoToGoalGoal
    // Serialize message field [x_pos]
    bufferInfo = _serializer.float64(obj.x_pos, bufferInfo);
    // Serialize message field [y_pos]
    bufferInfo = _serializer.float64(obj.y_pos, bufferInfo);
    // Serialize message field [theta]
    bufferInfo = _serializer.float64(obj.theta, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type GoToGoalGoal
    let tmp;
    let len;
    let data = new GoToGoalGoal();
    // Deserialize message field [x_pos]
    tmp = _deserializer.float64(buffer);
    data.x_pos = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [y_pos]
    tmp = _deserializer.float64(buffer);
    data.y_pos = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [theta]
    tmp = _deserializer.float64(buffer);
    data.theta = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'catbot_navigation/GoToGoalGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5af55a02225d2e56be88e5e3a36b4ce9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Definition of Goal Message
    
    float64 x_pos
    float64 y_pos
    float64 theta
    
    `;
  }

};

module.exports = GoToGoalGoal;
